### ISSUE TITLE
Header HTML is broken on main README

### ISSUE THREAD

**Issue by sfirke** [trinker/wakefield#13]
Earlier this month, GitHub changed how it renders Markdown and it no longer plays as nicely with HTML tags.  This is affecting this package's README landing page.

**Comment by trinker** [comment]
can you be more specific...what's not rendering correctly?

**Comment by sfirke** [comment]
Ah, the passage of time seems to have cured this.  In March, GitHub made a change that affected README .Rmd pages that used HTML tags - I found old commits to my own package repo from mid-March making a fix, around when I opened this issue here.  Sorry not to document my report better above.

Everything looks fine currently, so I think this is obsolete now.  Maybe GitHub patched it in the meantime.
