### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jonocarroll** [trinker/wakefield#15]
Not a major issue, but I was looking through `help(package = "wakefield")` for the function that added `NA` values. I entirely missed `r_na` because its documentation still says `Title`. 

https://github.com/trinker/wakefield/blob/1d14ca0b0b10652eeef9ebf6bae7e86a31c2168a/R/r_na.R

Ditto for `r_dummy`. Description is also missing. Great work on this package BTW.

**Comment by trinker** [comment]
@jonocarroll  Thanks...much appreciated.  Any chance you would do a pull request for this issue?

**Comment by jonocarroll** [comment]
I was going to do that, but didn't want to step on toes of how you wanted the functions described. Will if you want to take the risk though.

**Comment by trinker** [comment]
Seems to me that someone who came up with the idea of ggghost is not a risk :-)  I'd be most grateful.

**Comment by jonocarroll** [comment]
:blush: complimenting me will only get me to do your work .... oh, wait.

BRB.
