### ISSUE TITLE
Typo: empoyment in employment.R.

### ISSUE THREAD

**Issue by danilofreire** [trinker/wakefield#2]
Hi Tyler,

Thanks for your great package! It's very useful.

I've just noticed that there's a small spelling mistake in employment.R. In the script, the function is written as "empoyment", so it gives an error when you type it.

Best,
Danilo

**Comment by trinker** [comment]
@danilofreire Thanks for the catch.  Should be fixed now.  Please let me know if you catch anything else or if you have ideas for improvements.
