### ISSUE TITLE
An update to stringi 1.5.3 breaks wakefield

### ISSUE THREAD

**Issue by gagolews** [trinker/wakefield#25]
Apologies, but an updated version of https://github.com/gagolews/stringi/  unfortunately  breaks your package's checks, can you fix the following issues in the next release?

Change-log: https://cran.r-project.org/web/packages/stringi/NEWS: 

>  [DEPRECATION WARNING] `nparagraphs` in `stri_rand_lipsum()` has been renamed  `n_paragraphs`.

```
Package: wakefield
Check: examples
New result: ERROR
  Running examples in â€˜wakefield-Ex.Râ€™ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: lorem_ipsum
  > ### Title: Generate Random Lorem Ipsum Strings
  > ### Aliases: lorem_ipsum paragraph
  > ### Keywords: character string
  > 
  > ### ** Examples
  > 
  > lorem_ipsum(10)
  Error in stringi::stri_rand_lipsum(n = n, ...) : 
    argument 1 matches multiple formal arguments
  Calls: lorem_ipsum
  Execution halted
```

**Comment by trinker** [comment]
@gagolews Thanks for the heads up.  Fixing now.

**Comment by trinker** [comment]
https://github.com/trinker/wakefield/commit/faa3e181419059f6293169013023ab55dff1e825 fixes this
